# Generated by Django 3.0.7 on 2020-11-10 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('enrollment', models.BigIntegerField(unique=True, verbose_name='enrollment')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_HOD', models.BooleanField(default=False)),
                ('is_Faculty', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=10)),
                ('field', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='subjectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=30)),
                ('shortname', models.CharField(max_length=5)),
                ('semister', models.IntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Field')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=30)),
                ('video', models.FileField(upload_to='lecture/')),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.subjectList')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Enrollment')),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Classroom')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Field')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_HOD', models.BooleanField(default=False)),
                ('Enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Enrollment')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Field')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Faculty'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Field'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.subjectList'),
        ),
    ]
